---
- hosts: all
  become: true
  tasks:

    - name: update repository index & install apache & php (Ubuntu + Fedora)
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
