---
- hosts: all
  become: true
  tasks:
    - name: update repository index (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 package (Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install support for php (Ubuntu)
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: update repository index (Fedora)
      ansible.builtin.dnf:
        update_cache: yes
        use_backend: dnf4
      when: ansible_distribution == "Fedora"

    - name: install httpd package (Fedora)
      ansible.builtin.dnf:
        name: httpd
        state: latest
        use_backend: dnf4
      when: ansible_distribution == "Fedora"

    - name: install php support for apache (Fedora)
      ansible.builtin.dnf:
        name: php
        state: latest
        use_backend: dnf4
      when: ansible_distribution == "Fedora"
